recipeapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from .views import home, RecipesListView, RecipesDetailView, search

app_name = 'recipes'

urlpatterns = [
    path('', home),
    path('list/', RecipesListView.as_view(), name='list'),
    path('list/<pk>', RecipesDetailView.as_view(), name='detail'),
    path('recipes/', search, name='search')
]

recipes/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.
class Recipes(models.Model):
    name = models.CharField(max_length=120)
    cooking_time = models.IntegerField()
    ingredients = models.TextField()
    difficulty = models.CharField(max_length=120)
    pic = models.ImageField(upload_to="recipes", default="no_picture.png")

    def calculate_difficulty(self):
        ingredients = self.ingredients.split(', ')
        if self.cooking_time < 10 and len(ingredients) <= 4:
            difficulty = "Easy"
        elif self.cooking_time < 10 and len(ingredients) > 4:
            difficulty = "Medium"
        elif self.cooking_time >= 10 and len(ingredients) <= 4:
            difficulty = "Intermediate"
        elif self.cooking_time >= 10 and len(ingredients) > 4:
            difficulty = "Hard"
        return difficulty

    def ingredient_list(self):
        if self.ingredients=="":
            return []
        return self.ingredients.split(", ")
    
    def numb_of_ingredients(self):
        return len(self.ingredient_list())

    def __str__(self):
        return str(self.name)
    
    def get_absolute_url(self):
        return reverse ('recipes:detail', kwargs={'pk': self.pk})

users/models.py
from django.db import models

class User(models.Model):
    username = models.CharField(max_length=120, unique=True)
    name = models.CharField(max_length=120)
    password = models.CharField(max_length=120)
    bio = models.TextField()
    email = models.EmailField(null= True, blank=True, max_length=120)

    def __str__(self):
        return str(self.username)

recipes/forms.py
from django import forms

class RecipesSearchForm(forms.Form):
    recipe_name = forms.CharField(max_length=120)

recipeapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout  #library
from django.contrib.auth.forms import AuthenticationForm  #from for authentication

# create a Form object of class AuthForm
def login_view(request):
    #initialize error message to None
    error_message = None
    #form object with username and password field
    form = AuthenticationForm()

    # when the user hits "login" button, the POST request is generated
    if request.method == "POST":
        #read the data sent by the form via POST request
        form = AuthenticationForm(data = request.POST)

        #check if form is valid
        if form.is_valid():
            username =  form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            #use Django authenticate function to validate user
            user = authenticate(username=username, password=password)
            if user is not None:
                #use predefined django function to login
                login(request, user)
                return redirect('/list')
        else:
            error_message = "oops...something went wrong"
    #prepare data to send from view to template
    context ={
        'form': form,
        'error_message': error_message
    }

    #load the login page using "context" information
    return render(request, 'auth/login.html', context)

def logout_view(request):
    logout(request)
    return render(request, 'auth/success.html')

recipes/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Recipes
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from .forms import RecipesSearchForm
import pandas as pd
from .utils import get_chart

# Create your views here.
class RecipesListView(LoginRequiredMixin, ListView):
    model = Recipes
    template_name = 'recipes/main.html'

class RecipesDetailView(LoginRequiredMixin, DetailView):
    model = Recipes
    template_name = 'recipes/detail.html'

def home(request):
    return render(request, 'recipes/home.html')

@login_required
#define function-based view
def search(request):
    #create an instance of RecipesSearchForm
    form = RecipesSearchForm(request.POST or None)
    recipes = None
    recipes_df = None #initialize dataframe to None
    chart1 = None
    chart2 = None
    chart3 = None

    if request.method == 'POST':
        recipe_name = request.POST.get('recipe_name')
        #apply filter to extract data
        qs = Recipes.objects.filter(name__icontains=recipe_name)

        if qs:
            recipes = qs
            #convert the queryset values to pandas df
            recipes_df=pd.DataFrame(qs.values())
            
            #chart1
            chart1 = get_chart("plot", recipes_df)

            #chart2
            chart2_data = {
                "difficulty": ["Easy", "Medium", "Intermediate", "Hard"],
                "count": [0, 0, 0, 0]
            }
            for recipe in recipes:
                difficulty = recipe.calculate_difficulty()
                if difficulty in chart2_data["difficulty"]:
                    index = chart2_data["difficulty"].index(difficulty)
                    chart2_data["count"][index] += 1
            
            #filter out labels and counts with a count of 0
            filtered_labels = []
            filtered_counts = []
            for label, count in zip(chart2_data["difficulty"], chart2_data["count"]):
                if count > 0:
                    filtered_labels.append(label)
                    filtered_counts.append(count)
            
            #create new disctionary with filtered data
            filtered_chart2_data = {
                "difficulty": filtered_labels,
                "count": filtered_counts,
            }

            chart2 = get_chart("pie", filtered_chart2_data, labels=filtered_labels)

            #chart3
            chart3_data = {
                "name": [recipe.name for recipe in recipes],
                "nr_ingredients": [recipe.numb_of_ingredients() for recipe in recipes]
            }
            chart3 = get_chart("bar", chart3_data)

            #recipes_df=recipes_df.to_html()

    #pack up data to be sent to template in the context dictionary
    context={
        'form':form,
        'recipes': recipes,
        'chart1': chart1,
        'chart2': chart2,
        'chart3': chart3
    }
    #load the record.html page using the data
    return render(request, 'recipes/search.html', context)

users/views.py
from django.shortcuts import render

# Create your views here.

recipes/templates/recipes/detail.html
{% load static %}
<!DOCTYPE html>

<head>
    <title>{{object.name}} Recipe</title>
    <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/styles.css' %}">
    <style type="text/css">
        body {
            background: url("{% static 'recipes/images/background.jpg' %}");
            background-size: cover;
        }
    </style>
</head>
<header>
</header>

<body>
    <div class="nav-bar">
        <div class="navbar-left">
            <img src="{% static 'recipes/images/food_logo.png' %}" alt="logo" height="100px" width="100px">
        </div>
        <div class="navbar-right">
            <a href="{% url 'recipes:search' %}">Search</a>
            <h1></h1>
            <a href="{%url 'logout' %}">Logout</a>
        </div>
    </div>

    <div class="details-card">
        <h2>Details: {{object.name}}</h2>
        <img src="{{object.pic.url}}" class="recipe-image" />
        <div class="details-body">
            <b>Title: </b> {{object.name}} <br>
            <b>Cooking Time: </b> {{object.cooking_time}} minutes <br>
            <b>Difficulty: </b> {{object.calculate_difficulty}} <br>
            <b>Ingredients: </b> {{object.ingredients}} <br>
        </div>
        <button onclick="goBack()" class="custom-button">Back</button>
    </div>

</body>
<script>
    function goBack(){
        window.history.back();
    }
</script>

</html>

recipes/templates/recipes/home.html
{% load static %}

<!DOCTYPE html>
<html>
    <title>Recipes Home</title>
    <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/styles.css' %}">
    <style type="text/css">
        body {
            background: url("{% static 'recipes/images/background.jpg' %}");
            background-size: cover;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        h1,
        h3 {
            font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif text-align: center;
        }
    </style>

    <body>
        <nav>
            <img src="{% static 'recipes/images/food_logo.png' %}" alt="logo" height="200px" width="200px">
        </nav>

        <h1>Discover a world of culinary delights</h1>
        <h1>with our MoodForFood app</h1>
        <h3>Login to explore recipes ↓</h3>

        <button class="custom-button"><a href="{%url 'login' %}">Login</a></button>

    </body>

</html>

recipes/templates/recipes/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Recipes List</title>
    <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/styles.css' %}">
    <style type="text/css">
        body {
            background: url("{% static 'recipes/images/background.jpg' %}");
            background-size: cover;
        }
    </style>
</head>
<body>
    <div class="nav-bar">
        <div class="navbar-left">
            <img src="{% static 'recipes/images/food_logo.png' %}" alt="logo" height="100px" width="100px">
        </div>
        <div class="navbar-right">
            <a href="{% url 'recipes:search' %}">Search</a>
            <h1></h1>
            <a href="{%url 'logout' %}">Logout</a>
        </div>
    </div>

    <h1>Recipes List</h1>
    <div class="recipe-grid">
        {% for object in object_list %}
        <a href="{{object.get_absolute_url}}">
            <div class="recipe-card">
                <img src="{{object.pic.url}}" class="recipe-image">
                <h3>{{object.name}}</h3>
            </div>
        </a>
        {% endfor %}
    </div>
</body>

</html>

recipes/templates/recipes/search.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>Search</title>
    <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/styles.css' %}">
    <style type="text/css">
        body {
            background: url("{% static 'recipes/images/background.jpg' %}");
            background-size: cover;
        }
        table {
            margin: 0 20px;
        }
        table, th, td {
            border: 1px solid black;
        }
        th, td {
            padding: 10px;
            text-align: left;
        }
        th {
            font-weight: bold;
        }
        form {
            margin: 0 20px;
            display: flex;
            flex-direction: column;
            align-items: center;
        }
    </style>
</head>

<body>
    <div class="nav-bar">
        <div class="navbar-left">
            <img src="{% static 'recipes/images/food_logo.png' %}" alt="logo" height="100px" width="100px">
        </div>
        <div class="navbar-right"><a href="{%url 'logout' %}">Logout</a></div>
    </div>
    <h1>Search for recipes</h1>
    <hr>
    <form action="" method="POST">
        {% csrf_token %}
        {{form}}
        <button class="custom-button" type="submit">search</button>
    </form>
    <br>
    <div>
        {% if recipes %}
        <h2>Search results:</h2>
        <table>
            <thead>
                <tr>
                    <th>Recipe Name</th>
                    <th>Cooking Time</th>
                    <th>Ingredients</th>
                    <th>Difficulty</th>
                </tr>
            </thead>
            <tbody>
                {% for recipe in recipes %}
                <tr>
                    <td><a href="{% url 'recipes:detail' pk=recipe.id %}"> {{ recipe.name }}</a></td>
                    <td>{{recipe.cooking_time}}</td>
                    <td>{{recipe.ingredients}}</td>
                    <td>{{recipe.calculate_difficulty}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <h2>Cooking Time:</h2>
        <img src="data:image/png; base64, {{chart1|safe}}" alt="Plot Chart">
        <h2>Difficulty:</h2>
        <img src="data:imgae/png; base64, {{chart2|safe}}" alt="Pie Chart">
        <h2>Ingredients</h2>
        <img src="data:image/png; base64, {{chart3|safe}}" alt="Pie Chart">

        {% else %}
        <h3>No recipe found</h3>
        {% endif %}
    </div>
    <a href="{% url 'recipes:list' %}"><button class="custom-button">View all recipes</button></a>
</body>

</html>